---
title: "ProyekUTS - 2"
output: 
  html_document: 
    df_print: paged
date: '2022-04-13'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Load data & library

```{r load data & library}
library(dplyr)
library(ggplot2)
library(car)
library(lmtest)
library(broom)

data <- read.csv("E:\\Kuliah\\Statistika Multivariat dengan R\\Multivariat-R---Proyek-UTS\\NHANES_data.csv")
```

### Preprocessing

```{r preprocessing}
#Ubah angka pada data kategorik menjadi teks

#RIDRETH 
data$RIDRETH1 <- as.factor(data$RIDRETH1)
levels(data$RIDRETH1)[c(1,2,3,4,5)] <- c("Mexican", "Latino", "White", "Black", "Other")

#RIAGENDR
data$RIAGENDR <- as.factor(data$RIAGENDR)
levels(data$RIAGENDR)[c(1,2)] <- c("Male", "Female")

#DMDMARTL
data$DMDMARTL <- as.factor(data$DMDMARTL)
levels(data$DMDMARTL)[c(1,2,3,4,5,6)] <- c("Menikah", "Janda/Duda", "Bercerai", "Berpisah", "Belum Menikah", "Tinggal Bersama")

#FIAINTRP
data$FIAINTRP <- as.factor(data$FIAINTRP)
levels(data$FIAINTRP)[c(1,2)] <- c("Yes", "No")

#DMDEDUC2
data$DMDEDUC2 <- as.factor(data$DMDEDUC2)
levels(data$DMDEDUC2)[c(1,2,3,4,5)] <- c("Tidak tamat SMP", "Tamat SMP", "Tamat SMA", "Sarjana", "Pascasarjana")

#SMQ040
data$SMQ040 <- as.factor(data$SMQ040)
levels(data$SMQ040)[c(1,2,3)] <- c("Setiap hari", "Kadang-kadang", "Tidak merokok")
```

### Jumlah NA

```{r null value}
#Jumlah NA pada tiap kolom
data %>%
  select(everything()) %>%
  summarise_all(funs(sum(is.na(.))))

#Jumlah baris dengan setidaknya 1 NA
sum(is.na(data))
```

### Visualisasi univariat

```{r visualisasi univariat}
#BMXWT
ggplot(data, aes(x=BMXWT)) + 
  geom_boxplot() +
  ggtitle("Penyebaran Berat Badan (BMXWT)") +
  xlab("Berat badan")

#ALQ130
ggplot(data, aes(x=ALQ130)) + 
  geom_boxplot() +
  ggtitle("Penyebaran Rata-rata Banyaknya Minuman Alkohol (ALQ130)") +
  xlab("Rata-rata")

#RIDRETH1
ggplot(data, aes(x=RIDRETH1)) + 
  geom_bar(fill = "dodgerblue1") +
  ggtitle("Jumlah Responden Berdasarkan Ras (RIDRETH1)") +
  ylab("Jumlah") +
  xlab("Ras")

#DMDEDUC2
ggplot(data, aes(x=DMDEDUC2)) + 
  geom_bar(fill = "dodgerblue1") +
  ggtitle("Jumlah Responden Berdasarkan Tingkat Pendidikan (DMDEDUC2)") +
  ylab("Jumlah") +
  xlab("Tingkat Pendidikan")

#RIDAGEYR
ggplot(data, aes(x=RIDAGEYR)) + 
  geom_histogram(fill = "dodgerblue1") + 
  ggtitle("Jumlah Responden Berdasarkan Umur (RIDAGEYR)") +
  ylab("Jumlah") +
  xlab("Umur")

#DMDMARTL
ggplot(data, aes(x=DMDMARTL)) + 
  geom_bar(fill = "dodgerblue1") + 
  ggtitle("Jumlah Responden Berdasarkan Status Pernikahan (DMDMARTL)") +
  ylab("Jumlah") +
  xlab("Status Pernikahan")

#INDHHIN2
ggplot(data, aes(x=as.factor(INDHHIN2))) + 
  geom_bar(fill = "dodgerblue1") + 
  ggtitle("Jumlah Responden Berdasarkan Pendapatan Rumah Tangga Tahunan (INDHHIN2)") +
  ylab("Jumlah") +
  xlab("Pendapatan")

#RIAGENDR
gender_group = data %>%
  group_by(RIAGENDR) %>%
  summarise(val=n())

ggplot(gender_group, aes(x="", y=val, fill=factor(RIAGENDR))) +
  geom_bar(stat="identity", width=1) +
  coord_polar("y", start=0) +
  ggtitle("Jenis Kelamin Responden") +
  guides(fill=guide_legend("Gender"))

#SMQ040
smq_group = data %>%
  group_by(SMQ040) %>%
  summarise(val=n())

ggplot(smq_group, aes(x="", y=val, fill=factor(SMQ040))) +
  geom_bar(stat="identity", width=1) +
  coord_polar("y", start=0) +
  ggtitle("Seberapa Sering Responden Merokok Tembakau") +
  guides(fill=guide_legend("Status Merokok"))

#FIAINTRP
intrp_group = data %>%
  group_by(FIAINTRP) %>%
  summarise(val=n())

ggplot(intrp_group, aes(x="", y=val, fill=factor(FIAINTRP))) +
  geom_bar(stat="identity", width=1) +
  coord_polar("y", start=0) +
  ggtitle("Jumlah Responden yang Menggunakan Interpreter") +
  guides(fill=guide_legend("Interpreter"))
```

### Visualisasi bivariat

```{r visualisasi bivariat}
#Hubungan setiap kolom dengan berat badan

#Umur - Berat badan
ggplot(data, aes(x=RIDAGEYR, y=BMXWT)) +
  geom_point(colour="dodgerblue2") +
  ggtitle("Hubungan Berat Badan dan Umur") +
  ylab("Berat badan") +
  xlab("Umur")

#Kolom kategorikal dengan Berat badan
categorical_columns = c("RIAGENDR", "RIDRETH1", "SMQ040", "DMDEDUC2", "DMDMARTL", "FIAINTRP")

for(col in categorical_columns) {
  title <- sprintf("Berat Badan (BMXWT) Responden Berdasarkan \'%s\'", col)
  plot <- ggplot(data, aes_string(x=col, y="BMXWT")) +
    geom_boxplot() + 
    ggtitle(title) +
    ylab("Berat badan") +
    xlab(col)
  print(plot)
}

#Pendapatan - Berat badan
ggplot(data, aes(x=as.factor(INDHHIN2), y=BMXWT)) +
  geom_boxplot() +
  ggtitle("Berat Badan (BMXWT) Responden Berdasarkan \'INDHHIN2\'") +
  ylab("Berat badan") +
  xlab("INDHHIN2")

#Rata2 minuman alkohol - Berat badan
ggplot(data, aes(x=as.factor(ALQ130), y=BMXWT)) +
  geom_boxplot() +
  ggtitle("Berat Badan (BMXWT) Responden Berdasarkan \'ALQ130\'") +
  ylab("Berat badan") +
  xlab("ALQ130")
```

### Mengisi nilai NA

```{r fillNA prepare}

#kolom kelompok umur (AGEGRP)
data = data %>% 
  mutate(AGEGRP = cut_width(RIDAGEYR, width=10))

#fungsi untuk mencari modus
mode = function(v) {
  v = na.omit(v)
  unique_val = unique(v)
  unique_val[which.max(tabulate(match(v, unique_val)))]
}

#kolom yang digunakan untuk menetukan modus
column_name <- c("RIAGENDR", "RIDRETH1", "SMQ040", "DMDEDUC2", "DMDMARTL", "AGEGRP", "ALQ130")
```

```{r fillNA FIAINTRP}
#cari kolom paling berkorelasi
fiaintrp_chisq_pvalue <- c()
for(col in column_name){
  chisq = chisq.test(data$FIAINTRP, data[,col])
  fiaintrp_chisq_pvalue = append(fiaintrp_chisq_pvalue, chisq[["p.value"]])
}
df_fiaintrp_chisq <- data.frame(column_name, fiaintrp_chisq_pvalue)
df_fiaintrp_chisq
#paling berkorelasi --> RIDRETH1

#Hitung modus FIAINTRP untuk setiap kategori RIDRETH1
fiaintrp_mode_by_ridreth1 <- data %>% 
  group_by(RIDRETH1) %>% 
  summarise(Mode = mode(FIAINTRP))
fiaintrp_mode_by_ridreth1 = as.data.frame(fiaintrp_mode_by_ridreth1)
rownames(fiaintrp_mode_by_ridreth1) = fiaintrp_mode_by_ridreth1$RIDRETH1
fiaintrp_mode_by_ridreth1

#Ganti nilai NA pada kolom FIAINTRP dengan modus
for(i in 1:nrow(data)){
  if(is.na(data[i, "FIAINTRP"])){
    data[i, "FIAINTRP"] = fiaintrp_mode_by_ridreth1[data$RIDRETH1[i], "Mode"]
  }
}

```

```{r fillNA INDHHIN2}
#cari kolom paling berkorelasi
indhhin2_chisq_pvalue <- c()
for(col in column_name){
  chisq = chisq.test(data$INDHHIN2, data[,col])
  indhhin2_chisq_pvalue = append(indhhin2_chisq_pvalue, chisq[["p.value"]])
}
df_indhhin2_chisq <- data.frame(column_name, indhhin2_chisq_pvalue)
df_indhhin2_chisq
#paling berkorelasi --> DMDMARTL

#Hitung modus INDHHIN2 untuk setiap kategori DMDMARTL
indhhin2_mode_by_dmdmartl <- data %>% 
  group_by(DMDMARTL) %>% 
  summarise(Mode = mode(INDHHIN2))
indhhin2_mode_by_dmdmartl = as.data.frame(indhhin2_mode_by_dmdmartl)
rownames(indhhin2_mode_by_dmdmartl) = indhhin2_mode_by_dmdmartl$DMDMARTL
indhhin2_mode_by_dmdmartl

#Ganti nilai NA pada kolom INDHHIN2 dengan modus
for(i in 1:nrow(data)){
  if(is.na(data[i, "INDHHIN2"])){
    data[i, "INDHHIN2"] = indhhin2_mode_by_dmdmartl[data$DMDMARTL[i], "Mode"]
  }
}
```

### Korelasi untuk pembuatan model

```{r more than 2 categories}
#ANOVA

#RIDRETH1
summary(aov(BMXWT ~ RIDRETH1, data=data)) #

#SMQ040
summary(aov(BMXWT ~ SMQ040, data=data)) #

#DMDEDUC2
summary(aov(BMXWT ~ DMDEDUC2, data=data))

#DMDMARTL
summary(aov(BMXWT ~ DMDMARTL, data=data))

#INDHHIN2
summary(aov(BMXWT ~ INDHHIN2, data=data))
```

```{r only 2 categories}
#t.test 

#RIAGENDR
gender_male = data %>%
  filter(RIAGENDR == "Male")

gender_female = data %>%
  filter(RIAGENDR == "Female")

t.test(gender_male$BMXWT, gender_female$BMXWT) #

#FIAINTRP
intrp_yes = data %>%
  filter(FIAINTRP == "Yes")

intrp_no = data %>%
  filter(FIAINTRP == "No")

t.test(intrp_yes$BMXWT, intrp_no$BMXWT) #
```

```{r numerical}
#Spearman 

#RIDAGEYR
cor.test(data$BMXWT, data$RIDAGEYR, method = "spearman") #

#ALQ130
cor.test(data$BMXWT, data$ALQ130, method = "spearman") #
```

### Pembuatan Model

```{r model awal}
#variabel (kolom) yang memiliki korelasi dengan berat badan
variables_to_use <- c("RIDRETH1", "SMQ040", "RIAGENDR", "FIAINTRP", "RIDAGEYR", "ALQ130")

#model awal
linear_model <- lm(BMXWT ~ RIDRETH1 + SMQ040 + RIAGENDR + FIAINTRP + RIDAGEYR + ALQ130, data=data)
summary(linear_model)
```

```{r model awal (2)}
#hapus RIDRETH1, nilai p-value besar
linear_model <- lm(BMXWT ~ SMQ040 + RIAGENDR + FIAINTRP + RIDAGEYR + ALQ130, data=data)
summary(linear_model)
```

### Plot Interaksi

```{r}
#variabel kategorik untuk diperiksa interaksi
variables_to_use_categorical = c("RIDRETH1", "SMQ040", "RIAGENDR", "FIAINTRP")

c <- combn(variables_to_use_categorical, 2)
i <- 1
while(i <= dim(c)[2]){
  interaction.plot(x.factor = data[[c[1,i]]],
                 trace.factor = data[[c[2,i]]],
                 response = data[["BMXWT"]],
                 fun = median,
                 ylab = "BMXWT",
                 xlab = c[1,i],
                 lwd = 2,
                 trace.label = c[2,i])
  
  interaction.plot(x.factor = data[[c[2,i]]],
                 trace.factor = data[[c[1,i]]],
                 response = data[["BMXWT"]],
                 fun = median,
                 ylab = "BMXWT",
                 xlab = c[2,i],
                 lwd = 1,
                 trace.label = c[1,i])
  i = i + 1
}

#Berinteraksi => SMQ040*RIDRETH1, FIAINTRP*RIDRETH1, RIAGENDR*SMQ040, FIAINTRP*RIAGENDR
#SMQ040:RIDRETH1 + RIDRETH1:SMQ040 + RIDRETH1:RIAGENDR + FIAINTRP:RIDRETH1 + RIDRETH1:FIAINTRP + RIAGENDR:SMQ040 + SMQ040:RIAGENDR + SMQ040:FIAINTRP + FIAINTRP:RIAGENDR + RIAGENDR:FIAINTRP
```

### Stepwise 1

```{r}
#Stepwise dari model dengan interaksi
linear_model1 <- lm(BMXWT ~ RIDAGEYR + ALQ130 + RIDRETH1*SMQ040 + RIDRETH1*FIAINTRP + SMQ040*RIAGENDR + RIAGENDR*FIAINTRP, data=data)
stepwise1 <- step(linear_model1,direction = "both")

summary(stepwise1)
AIC(stepwise1)
```

```{r}
#Uji model
plot(stepwise1)

#normalitas
shapiro.test(stepwise1$residuals)

#Breusch-Pagan test
bptest(stepwise1)

#independensi
vif(stepwise1)

#cek outlier
outlierTest(stepwise1)
```

### Stepwise 2 - Hapus outlier

```{r}
#hapus outlier dengan p-value paling kecil
data2 <- data[-c(1020),]

stepwise2 <- lm(BMXWT ~ RIDAGEYR + ALQ130 + RIDRETH1 + SMQ040 + FIAINTRP + RIAGENDR + SMQ040:RIAGENDR, data=data2)

summary(stepwise2)
AIC(stepwise2)
```

```{r}
#Uji model
plot(stepwise2)

#normalitas
shapiro.test(stepwise2$residuals)

#Breusch-Pagan test
bptest(stepwise2)

#independensi
vif(stepwise2)

#cek outlier
outlierTest(stepwise2)
```

### Stepwise 3 - Hapus 3 outlier

```{r}
data3 <- data[-c(1020, 617, 735, 703),]

stepwise3 <- lm(BMXWT ~ RIDAGEYR + ALQ130 + RIDRETH1 + SMQ040 + FIAINTRP + RIAGENDR + SMQ040:RIAGENDR, data=data3)

summary(stepwise3)
AIC(stepwise3)
```

```{r}
#Uji model
plot(stepwise3)

#normalitas
shapiro.test(stepwise3$residuals)

#Breusch-Pagan test
bptest(stepwise3)

#independensi
vif(stepwise3)

#cek outlier
outlierTest(stepwise3)
```

### Stepwise 4 - Hapus outlier baru

```{r}
data4 <- data[-c(1020, 617, 735, 703, 977),]

stepwise4 <- lm(BMXWT ~ RIDAGEYR + ALQ130 + RIDRETH1 + SMQ040 + FIAINTRP + RIAGENDR + SMQ040:RIAGENDR, data=data4)

summary(stepwise4)
AIC(stepwise4)
```

```{r}
#Uji model
plot(stepwise4)

#normalitas
shapiro.test(stepwise4$residuals)

#Breusch-Pagan test
bptest(stepwise4)

#independensi
vif(stepwise4)

#cek outlier
outlierTest(stepwise4)
```

### Stepwise Log

```{r}
#berdasarkan data 4 + hapus baris 722
data5 <- data[-c(1020, 617, 735, 703, 977, 722),]

stepwise_log <- lm(log(BMXWT) ~ RIDAGEYR + ALQ130 + RIDRETH1 + SMQ040 + FIAINTRP + RIAGENDR + SMQ040:RIAGENDR, data=data5)

summary(stepwise_log)
AIC(stepwise_log)
```

```{r}
#Uji model
plot(stepwise_log)

#normalitas
shapiro.test(stepwise_log$residuals)

#Breusch-Pagan test
bptest(stepwise_log)

#independensi
vif(stepwise_log)

#cek outlier
outlierTest(stepwise_log)
```

### Stepwise sqrt

```{r}
#berdasarkan model 4
data4 <- data[-c(1020, 617, 735, 703, 977, 722),]

linear_model_sqrt <- lm(sqrt(BMXWT) ~ SMQ040 + RIAGENDR + FIAINTRP + RIDAGEYR + ALQ130 + RIDRETH1:SMQ040 + RIDRETH1:FIAINTRP + SMQ040:RIAGENDR + RIAGENDR:FIAINTRP, data=data4)
stepwise_sqrt <- step(linear_model_sqrt, direction = "both")

summary(stepwise_sqrt)
AIC(stepwise_sqrt)
```

```{r}
#Uji model
plot(stepwise_sqrt)

#normalitas
shapiro.test(stepwise_sqrt$residuals)

#Breusch-Pagan test
bptest(stepwise_sqrt)

#independensi
vif(stepwise_sqrt)

#cek outlier
outlierTest(stepwise_sqrt)
```
