---
title: "ProyekUTS"
output: 
  html_document: 
    df_print: paged
date: '2022-03-19'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r data load & preprocessing}
#Load dataset
data = read.csv("E:\\Kuliah\\Statistika Multivariat dengan R\\Multivariat-R---Proyek-UTS\\NHANES_data.csv")

#Rename categorical number 

#RIDRETH 
data$RIDRETH1 = as.factor(data$RIDRETH1)
levels(data$RIDRETH1)[c(1,2,3,4,5)] <- c("Mexican", "Latino", "White", "Black", "Other")

#RIAGENDR
data$RIAGENDR = as.factor(data$RIAGENDR)
levels(data$RIAGENDR)[c(1,2)] <- c("Male", "Female")

#DMDMARTL
data$DMDMARTL = as.factor(data$DMDMARTL)
levels(data$DMDMARTL)[c(1,2,3,4,5,6)] <- c("Menikah", "Janda/Duda", "Bercerai", "Berpisah", "Belum Menikah", "Tinggal Bersama")

#FIAINTRP
data$FIAINTRP = as.factor(data$FIAINTRP)
levels(data$FIAINTRP)[c(1,2)] <- c("Yes", "No")

#DMDEDUC2
data$DMDEDUC2 = as.factor(data$DMDEDUC2)
levels(data$DMDEDUC2)[c(1,2,3,4,5)] <- c("Tidak tamat SMP", "Tamat SMP", "Tamat SMA", "Sarjana", "Pascasarjana")

#SMQ040
data$SMQ040 = as.factor(data$SMQ040)
levels(data$SMQ040)[c(1,2,3)] <- c("Setiap hari", "Kadang-kadang", "Tidak merokok")


#Count na values
sum(is.na(data$FIAINTRP))
sum(is.na(data$INDHHIN2))
sum(is.na(data))
```

```{r univariate}
library(ggplot2)
library(dplyr)

#visualization

#BMXWT
ggplot(data, aes(x=BMXWT)) + 
  geom_boxplot() +
  ggtitle("Penyebaran Berat Badan (BMXWT)") +
  xlab("Berat badan")

#ALQ130
ggplot(data, aes(x=ALQ130)) + 
  geom_boxplot() +
  ggtitle("Penyebaran Rata-rata Banyaknya Minuman Alkohol (ALQ130)") +
  xlab("Rata-rata")

#RIDRETH1
ggplot(data, aes(x=RIDRETH1)) + 
  geom_bar(fill = "dodgerblue1") +
  ggtitle("Jumlah Responden Berdasarkan Ras (RIDRETH1)") +
  ylab("Jumlah") +
  xlab("Ras")

#DMDEDUC2
ggplot(data, aes(x=DMDEDUC2)) + 
  geom_bar(fill = "dodgerblue1") +
  ggtitle("Jumlah Responden Berdasarkan Tingkat Pendidikan (DMDEDUC2)") +
  ylab("Jumlah") +
  xlab("Tingkat Pendidikan")

#RIDAGEYR
ggplot(data, aes(x=RIDAGEYR)) + 
  geom_histogram(fill = "dodgerblue1") + 
  ggtitle("Jumlah Responden Berdasarkan Umur (RIDAGEYR)") +
  ylab("Jumlah") +
  xlab("Umur")

#DMDMARTL
ggplot(data, aes(x=DMDMARTL)) + 
  geom_bar(fill = "dodgerblue1") + 
  ggtitle("Jumlah Responden Berdasarkan Status Pernikahan (DMDMARTL)") +
  ylab("Jumlah") +
  xlab("Status Pernikahan")

#INDHHIN2
ggplot(data, aes(x=as.factor(INDHHIN2))) + 
  geom_bar(fill = "dodgerblue1") + 
  ggtitle("Jumlah Responden Berdasarkan Pendapatan Rumah Tangga Tahunan (INDHHIN2)") +
  ylab("Jumlah") +
  xlab("Pendapatan")

#RIAGENDR
gender_group = data %>%
  group_by(RIAGENDR) %>%
  summarise(val=n())

ggplot(gender_group, aes(x="", y=val, fill=factor(RIAGENDR))) +
  geom_bar(stat="identity", width=1) +
  coord_polar("y", start=0) +
  ggtitle("Jenis Kelamin Responden") +
  guides(fill=guide_legend("Gender"))

#SMQ040
smq_group = data %>%
  group_by(SMQ040) %>%
  summarise(val=n())

ggplot(smq_group, aes(x="", y=val, fill=factor(SMQ040))) +
  geom_bar(stat="identity", width=1) +
  coord_polar("y", start=0) +
  ggtitle("Seberapa Sering Responden Merokok Tembakau") +
  guides(fill=guide_legend("Status Merokok"))

#FIAINTRP
intrp_group = data %>%
  group_by(FIAINTRP) %>%
  summarise(val=n())

ggplot(intrp_group, aes(x="", y=val, fill=factor(FIAINTRP))) +
  geom_bar(stat="identity", width=1) +
  coord_polar("y", start=0) +
  ggtitle("Jumlah Responden yang Menggunakan Interpreter") +
  guides(fill=guide_legend("Interpreter"))
```

```{r bivariate}
#Umur - Berat badan
ggplot(data, aes(x=RIDAGEYR, y=BMXWT)) +
  geom_point(colour="dodgerblue2") +
  ggtitle("Hubungan Berat Badan dan Umur") +
  ylab("Berat badan") +
  xlab("Umur")

#Kolom kategorikal dengan Berat badan
categorical_columns = c("RIAGENDR", "RIDRETH1", "SMQ040", "DMDEDUC2", "DMDMARTL", "FIAINTRP")

for(col in categorical_columns) {
  title = sprintf("Berat Badan (BMXWT) Responden Berdasarkan \'%s\'", col)
  plot = ggplot(data, aes_string(x=col, y="BMXWT")) +
    geom_boxplot() + 
    ggtitle(title) +
    ylab("Berat badan") +
    xlab(col)
  print(plot)
}

#Pendapatan - Berat badan
ggplot(data, aes(x=as.factor(INDHHIN2), y=BMXWT)) +
  geom_boxplot() +
  ggtitle("Berat Badan (BMXWT) Responden Berdasarkan \'INDHHIN2\'") +
  ylab("Berat badan") +
  xlab("INDHHIN2")

#Rata2 minuman alkohol - Berat badan
ggplot(data, aes(x=as.factor(ALQ130), y=BMXWT)) +
  geom_boxplot() +
  ggtitle("Berat Badan (BMXWT) Responden Berdasarkan \'ALQ130\'") +
  ylab("Berat badan") +
  xlab("ALQ130")

```
```{r fill null value}
#create AGEGRP
data = data %>% 
  mutate(AGEGRP = cut_width(RIDAGEYR, width=10))

#get mode function
mode = function(v) {
  v = na.omit(v)
  unique_val = unique(v)
  unique_val[which.max(tabulate(match(v, unique_val)))]
}

column_name = c("RIAGENDR", "RIDRETH1", "SMQ040", "DMDEDUC2", "DMDMARTL", "AGEGRP")

#FIAINTRP
fiaintrp_chisq_pvalue = c()
for(col in column_name){
  chisq = chisq.test(data$FIAINTRP, data[,col])
  fiaintrp_chisq_pvalue = append(fiaintrp_chisq_pvalue, chisq[["p.value"]])
}
df_fiaintrp_chisq = data.frame(column_name, fiaintrp_chisq_pvalue)

fiaintrp_mode_by_ridreth1 = data %>% 
  group_by(RIDRETH1) %>% 
  summarise(Mode = mode(FIAINTRP))
fiaintrp_mode_by_ridreth1 = as.data.frame(fiaintrp_mode_by_ridreth1)
rownames(fiaintrp_mode_by_ridreth1) = fiaintrp_mode_by_ridreth1$RIDRETH1

for(i in 1:nrow(data)){
  if(is.na(data[i, "FIAINTRP"])){
    data[i, "FIAINTRP"] = fiaintrp_mode_by_ridreth1[data$RIDRETH1[i], "Mode"]
  }
}

#INDHHIN2
indhhin2_chisq_pvalue = c()
for(col in column_name){
  chisq = chisq.test(data$INDHHIN2, data[,col])
  indhhin2_chisq_pvalue = append(indhhin2_chisq_pvalue, chisq[["p.value"]])
}
df_indhhin2_chisq = data.frame(column_name, indhhin2_chisq_pvalue)

indhhin2_mode_by_smq040 = data %>% 
  group_by(SMQ040) %>% 
  summarise(Mode = mode(INDHHIN2))
indhhin2_mode_by_smq040 = as.data.frame(indhhin2_mode_by_smq040)
rownames(indhhin2_mode_by_smq040) = indhhin2_mode_by_smq040$SMQ040

for(i in 1:nrow(data)){
  if(is.na(data[i, "INDHHIN2"])){
    data[i, "INDHHIN2"] = indhhin2_mode_by_smq040[data$SMQ040[i], "Mode"]
  }
}
```

```{r}
#anova - categorical with more than 2 groups
summary(aov(BMXWT ~ RIDRETH1, data=data)) #
summary(aov(BMXWT ~ SMQ040, data=data)) #
summary(aov(BMXWT ~ DMDEDUC2, data=data))
summary(aov(BMXWT ~ DMDMARTL, data=data))
summary(aov(BMXWT ~ INDHHIN2, data=data))
```
```{r}
#t.test - categorical with only 2 groups

#Gender
gender_male = data %>%
  filter(RIAGENDR == "Male")

gender_female = data %>%
  filter(RIAGENDR == "Female")

t.test(gender_male$BMXWT, gender_female$BMXWT) #

#Interpreter
intrp_yes = data %>%
  filter(FIAINTRP == "Yes")

intrp_no = data %>%
  filter(FIAINTRP == "No")

t.test(intrp_yes$BMXWT, intrp_no$BMXWT) #
```
```{r}
#spearman correlation - numerical data

#Age
cor.test(data$BMXWT, data$RIDAGEYR, method = "spearman") #

#Alcohol
cor.test(data$BMXWT, data$ALQ130, method = "spearman") #
```

```{r}
variables_to_use = c("RIDRETH1", "SMQ040", "RIAGENDR", "FIAINTRP", "RIDAGEYR", "ALQ130")

#model 1
linear_model = lm(BMXWT ~ RIDRETH1 + SMQ040 + RIAGENDR + FIAINTRP + RIDAGEYR + ALQ130, data=data)
summary(linear_model)

#remove 'RIDRETH1'
linear_model = lm(BMXWT ~ SMQ040 + RIAGENDR + FIAINTRP + RIDAGEYR + ALQ130, data=data)
summary(linear_model)
```
```{r}
#interaction plot

variables_to_use_categorical = c("RIDRETH1", "SMQ040", "RIAGENDR", "FIAINTRP")

c = combn(variables_to_use_categorical, 2)
i = 1
while(i <= dim(c)[2]){
  interaction.plot(x.factor = data[[c[1,i]]],
                 trace.factor = data[[c[2,i]]],
                 response = data[["BMXWT"]],
                 fun = median,
                 ylab = "BMXWT",
                 xlab = c[1,i],
                 lwd = 2,
                 trace.label = c[2,i])
  i = i + 1
}

```
```{r}
linear_model1 = lm(BMXWT ~ SMQ040 + RIAGENDR + FIAINTRP + RIDAGEYR + ALQ130 + RIDRETH1*SMQ040 + RIDRETH1*FIAINTRP + SMQ040*RIAGENDR + RIAGENDR*FIAINTRP, data=data)
stepwise1 <- step(linear_model1,direction = "both")

summary(stepwise1)
```
```{r}
library(broom)
model.diag.metrics = augment(stepwise1)
head(model.diag.metrics, 10)

plot(stepwise1, 1)
plot(stepwise1, 2)

shapiro.test(stepwise1$residuals)
```

```{r}
plot(stepwise1, 3)

library(lmtest)
bptest(stepwise1)
```
```{r}
boxplot(stepwise1$residuals)
boxplot.stats(stepwise1$residuals)$out

library(car)
outlierTest(stepwise)
```

```{r}
data1 = data[-c(1020),]
linear_model2 = lm(BMXWT ~ SMQ040 + RIAGENDR + FIAINTRP + RIDAGEYR + ALQ130 + RIDRETH1*SMQ040 + RIDRETH1*FIAINTRP + SMQ040*RIAGENDR + RIAGENDR*FIAINTRP, data=data1)
stepwise2 <- step(linear_model2, direction = "both")
```

```{r}
model.diag.metrics = augment(stepwise2)
head(model.diag.metrics, 10)

plot(stepwise2, 1)
plot(stepwise2, 2)

shapiro.test(stepwise2$residuals)
```
```{r}
data100 = data[-c(53,79,80,147,220,257,304,323,357,430,437,505,514,545,601,614,617,624,631,669,684,695,703,722,734,735,765,848,849,902,977,1020,47,171,433,858,950,1039,1066,564,208),] 
str(data100)
linear_model100 = lm(BMXWT ~ SMQ040 + RIAGENDR + FIAINTRP + RIDAGEYR + ALQ130 + RIDRETH1*SMQ040 + RIDRETH1*FIAINTRP + SMQ040*RIAGENDR + RIAGENDR*FIAINTRP, data=data100)
summary(linear_model100)
stepwise100<- step(linear_model100,direction = "both")

AIC(linear_model100)
AIC(stepwise100)
library(broom)
model.diag.metrics <- augment(stepwise100)

head(model.diag.metrics,10)
##Cara panggil nilai residual dan fitted values manual
head(stepwise100$residuals, 10)
head(stepwise100$fitted.values, 10)
plot(stepwise100,1)
#uji normalitas memakai shapiro
plot(stepwise100,2)
resid100<- stepwise100$residuals
shapiro.test(resid100)
# uji homokedastik
library(lmtest)
bptest(stepwise100)


#OUTLIERS
resid100<-stepwise100$residuals
bon100<- rstudent(stepwise100)
boxplot(resid100)
boxplot.stats(resid100)$out


#Bonferroni Outlier Test
library(car)
outlierTest(stepwise100)
```

```{r}
#log
linear_model100log = lm(log(BMXWT) ~ SMQ040 + RIAGENDR + FIAINTRP + RIDAGEYR + ALQ130 + RIDRETH1*SMQ040 + RIDRETH1*FIAINTRP + SMQ040*RIAGENDR + RIAGENDR*FIAINTRP, data=data100)
summary(linear_model100)
stepwise100log<- step(linear_model100log, direction = "both")

AIC(linear_model100log)
AIC(stepwise100log)
library(broom)
model.diag.metrics <- augment(stepwise100log)

head(model.diag.metrics,10)
##Cara panggil nilai residual dan fitted values manual
head(stepwise100log$residuals, 10)
head(stepwise100log$fitted.values, 10)
plot(stepwise100log,1)
#uji normalitas memakai shapiro
plot(stepwise100log,2)
resid100<- stepwise100log$residuals
shapiro.test(resid100)
# uji homokedastik
library(lmtest)
bptest(stepwise100log)


#OUTLIERS
resid100<-stepwise100log$residuals
bon100<- rstudent(stepwise100log)
boxplot(resid100)
boxplot.stats(resid100)$out


#Bonferroni Outlier Test
library(car)
outlierTest(stepwise100log)
```
```{r}
#log2 hapus outlier
data100log = data[-c(53,79,80,147,220,257,304,323,357,430,437,505,514,545,601,614,617,624,631,669,684,695,703,722,734,735,765,848,849,902,977,1020,47,171,433,858,950,1039,1066,564,208,13,565),]

linear_model100log2 = lm(log(BMXWT) ~ SMQ040 + RIAGENDR + FIAINTRP + RIDAGEYR + ALQ130 + RIDRETH1*SMQ040 + RIDRETH1*FIAINTRP + SMQ040*RIAGENDR + RIAGENDR*FIAINTRP, data=data100log)
summary(linear_model100log2)
stepwise100log2 <- step(linear_model100log2, direction = "both")

AIC(linear_model100log2)
AIC(stepwise100log2)
library(broom)
model.diag.metrics <- augment(stepwise100log2)

head(model.diag.metrics,10)
##Cara panggil nilai residual dan fitted values manual
head(stepwise100log2$residuals, 10)
head(stepwise100log2$fitted.values, 10)
plot(stepwise100log2,1)
#uji normalitas memakai shapiro
plot(stepwise100log2,2)
resid100<- stepwise100log2$residuals
shapiro.test(resid100)

plot(stepwise100log2,5)

# uji homokedastik
library(lmtest)
bptest(stepwise100log2)


#OUTLIERS
resid100<-stepwise100log2$residuals
bon100<- rstudent(stepwise100log2)
boxplot(resid100)
boxplot.stats(resid100)$out


#Bonferroni Outlier Test
library(car)
outlierTest(stepwise100log2)
```

```{r}
#boxcox
library(MASS)
linear_model100 = lm(BMXWT ~ SMQ040 + RIAGENDR + FIAINTRP + RIDAGEYR + ALQ130 + RIDRETH1*SMQ040 + RIDRETH1*FIAINTRP + SMQ040*RIAGENDR + RIAGENDR*FIAINTRP, data=data100)
summary(linear_model100)
stepwise100<- step(linear_model100,direction = "both")

stepwise100box = boxcox(stepwise100)
```
```{r}
linear_model100_0.2 = lm(BMXWT^0.2 ~ SMQ040 + RIAGENDR + FIAINTRP + RIDAGEYR + ALQ130 + RIDRETH1*SMQ040 + RIDRETH1*FIAINTRP + SMQ040*RIAGENDR + RIAGENDR*FIAINTRP, data=data100)
summary(linear_model100_0.2)
stepwise100_0.2 <- step(linear_model100_0.2, direction = "both")

AIC(linear_model100_0.2)
AIC(stepwise100_0.2)
library(broom)
model.diag.metrics <- augment(stepwise100_0.2)

head(model.diag.metrics,10)
##Cara panggil nilai residual dan fitted values manual
head(stepwise100_0.2$residuals, 10)
head(stepwise100_0.2$fitted.values, 10)
plot(stepwise100_0.2,1)
#uji normalitas memakai shapiro
plot(stepwise100_0.2,2)

resid100<- stepwise100_0.2$residuals
shapiro.test(resid100)
# uji homokedastik
library(lmtest)
bptest(stepwise100_0.2)


#OUTLIERS
resid100<-stepwise100_0.2$residuals
bon100<- rstudent(stepwise100_0.2)
boxplot(resid100)
boxplot.stats(resid100)$out


#Bonferroni Outlier Test
library(car)
outlierTest(stepwise100_0.2)
```








